### PR TITLE
59 manage user access

### PR DESCRIPTION
**Pull request by riddhighate-tamu**
Change user access management view

## Description
1. Updated the user access management view to include two different columns for read and write.
2. Each column has a "Select All" and a "Revoke All" button.

## How has this been tested?
1. The changes were tested locally on the rails server.
2. The Rspec and cucumber scenarios are passing.

## Screenshots (if appropriate):
User-access view:

Screenshot 2024-10-18 at 7 10 32 PM

&nbsp;

SimpleCov report:

image

## Checklist:

- [x] Zero `rubocop` violations
- [x] My code receives an "A" when `rubycritic` is run
- [x] >90% test coverage of my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Review by maxsmith271346 — COMMENTED** [review]
I didn't look too thoroughly. Do you guys sync the app and GitHub permissioning (both updating GitHub with our changes, and updating our permissions with GitHub changes)?

**Comment by maxsmith271346** [comment]
Please submit a picture of the simplecov for your tests.

**Comment by maxsmith271346** [comment]
If I check "write", is "read" automatically checked? And if I un-check "read", is "write" automatically un-checked?

**Comment by maxsmith271346** [comment]
> I didn't look too thoroughly. Do you guys sync the app and GitHub permissioning (both updating GitHub with our changes, and updating our permissions with GitHub changes)?
> 
> 
> 
> Mainak: No, Max, as I had mentioned it earlier,  incorporating the necessary code changes for this syncing operation would take a good amount of time, as Riddhi faced some problems with testing the permission-based APIs in Sprint 1.

Okay, no worries. I think that a good goal for sprint 3 will be GitHub syncing then.

**Review by masarkar-tamu — DISMISSED** [review]

**Review by masarkar-tamu — APPROVED** [review]

**Pull request merged**
