### PR TITLE
added a module to avoid duplication

### PR DESCRIPTION
**Pull request by riddhighate-tamu**
Module to avoid code duplication 

## Description
1. Added a module in concerns to avoid duplication 

## How has this been tested?
1. Tested locally and using rspec and cucumber.

## Screenshots (if appropriate):
Screenshot 2024-10-24 at 10 43 12 AM

## Checklist:

- [x] Zero `rubocop` violations
- [x] My code receives an "A" when `rubycritic` is run
- [x] >90% test coverage of my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by maxsmith271346** [comment]
Why is rubycritic failing?

**Comment by maxsmith271346** [comment]
@riddhighate-tamu what's causing the low coverage in `AssignmentsController`?

**Review by maxsmith271346 — COMMENTED** [review]
@riddhighate-tamu what's causing the low coverage in `AssignmentsController`?

**Comment by riddhighate-tamu** [comment]
> @riddhighate-tamu what's causing the low coverage in `AssignmentsController`?

`create_and_download_zip` function is not tested and that's what is causing the low coverage.

**Review by masarkar-tamu — APPROVED** [review]

**Review by maxsmith271346 — APPROVED** [review]

**Pull request merged**
